version: '3.8'

services:
  # Servicio para desarrollo
  app-dev:
    build:
      context: .
      target: build
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
    profiles:
      - dev

  # Servicio para producción
  app-prod:
    build:
      context: .
      target: production
    ports:
      - "80:80"
    restart: unless-stopped
    profiles:
      - prod

  # Servicio alternativo para desarrollo con hot reload
  app-dev-vite:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - NODE_ENV=development
    profiles:
      - dev-vite